# schemes_data.py
# Comprehensive verified government schemes dataset for SchemeSathi.ai

SCHEMES = [
    {
        "id": "pm_vishwakarma",
        "name": "PM Vishwakarma Scheme",
        "ministry": "Ministry of Micro, Small and Medium Enterprises",
        "min_age": 18,
        "max_age": 70,
        "gender": ["Male", "Female", "Other"],
        "categories": ["General", "OBC", "SC", "ST"],
        "max_income": 300000,
        "states": ["All"],
        "area": ["Rural", "Urban"],
        "business_status": ["New", "Existing"],
        "sectors": ["Handicraft", "Artisan", "Carpentry", "Blacksmith", "Tailoring", "Pottery"],
        "subsidy_rate": "Collateral-free enterprise loan up to ₹3 Lakh at 5% interest",
        "benefits": "Skill training with ₹500/day stipend, ₹15,000 modern toolkit grant, PM Vishwakarma Certificate.",
        "documents": ["Aadhaar Card", "Active Mobile Number", "Bank Account Details", "Ration Card (Family Verification)"],
        "application_mode": "Online (via Common Service Centres)",
        "official_url": "https://pmvishwakarma.gov.in/"
    },
    {
        "id": "pmegp",
        "name": "Prime Minister Employment Generation Programme (PMEGP)",
        "ministry": "Ministry of Micro, Small and Medium Enterprises",
        "min_age": 18,
        "max_age": 60,
        "gender": ["Male", "Female", "Other"],
        "categories": ["General", "OBC", "SC", "ST"],
        "max_income": 1000000,
        "states": ["All"],
        "area": ["Rural", "Urban"],
        "business_status": ["New"],
        "sectors": ["Manufacturing", "Services", "Handicraft", "Agro-processing"],
        "subsidy_rate": "15% to 35% margin money subsidy",
        "benefits": "Subsidy support for project loans up to ₹50 Lakh (Manufacturing) and ₹20 Lakh (Services).",
        "documents": ["Aadhaar Card", "PAN Card", "Project Report (DPR)", "Caste Certificate", "EDP Training Certificate"],
        "application_mode": "Online",
        "official_url": "https://www.kviconline.gov.in/pmegpeportal/"
    },
    {
        "id": "standup_india",
        "name": "Stand-Up India Scheme",
        "ministry": "Ministry of Finance",
        "min_age": 18,
        "max_age": 65,
        "gender": ["Female"],  # Males strictly eligible only if SC/ST
        "categories": ["SC", "ST", "General", "OBC"],
        "max_income": 2500000,
        "states": ["All"],
        "area": ["Rural", "Urban"],
        "business_status": ["New"],
        "sectors": ["Manufacturing", "Services", "Handicraft", "Trading", "Agri-allied"],
        "subsidy_rate": "Composite Bank Loan from ₹10 Lakh to ₹1 Crore",
        "benefits": "Covers 85% of total project cost for greenfield enterprises led by SC, ST, or women entrepreneurs.",
        "documents": ["Identity Proof", "Address Proof", "Caste Certificate (if applicable)", "Project Proposal", "Partnership Deed / MOA (if entity)"],
        "application_mode": "Online",
        "official_url": "https://www.standupmitra.in/"
    },
    {
        "id": "mudra_shishu",
        "name": "Pradhan Mantri Mudra Yojana (PMMY) - Shishu & Kishore",
        "ministry": "Ministry of Finance",
        "min_age": 18,
        "max_age": 65,
        "gender": ["Male", "Female", "Other"],
        "categories": ["General", "OBC", "SC", "ST"],
        "max_income": 600000,
        "states": ["All"],
        "area": ["Rural", "Urban"],
        "business_status": ["New", "Existing"],
        "sectors": ["Handicraft", "Services", "Small Retail", "Manufacturing", "Food Processing"],
        "subsidy_rate": "Collateral-free loans from ₹50,000 up to ₹5 Lakh",
        "benefits": "Instant working capital credit through Mudra Debit Card with no processing charges.",
        "documents": ["Identity Proof (Voter ID/Aadhaar)", "Proof of Business Address", "Machinery or Equipment Quotation"],
        "application_mode": "Online (Udyamimitra) / Bank Branch",
        "official_url": "https://www.mudra.org.in/"
    },
    {
        "id": "pm_svanidhi",
        "name": "PM Street Vendor's AtmaNirbhar Nidhi (PM SVANidhi)",
        "ministry": "Ministry of Housing and Urban Affairs",
        "min_age": 18,
        "max_age": 60,
        "gender": ["Male", "Female", "Other"],
        "categories": ["General", "OBC", "SC", "ST"],
        "max_income": 300000,
        "states": ["All"],
        "area": ["Urban"],
        "business_status": ["Existing"],
        "sectors": ["Street Vending", "Small Retail", "Services"],
        "subsidy_rate": "7% Interest Subsidy + Cashback on digital transactions",
        "benefits": "Collateral-free working capital loan starting at ₹10,000, scaling to ₹20,000 and ₹50,000 on timely repayment.",
        "documents": ["Urban Local Body (ULB) Vending Certificate", "Aadhaar Card", "Bank Account Details"],
        "application_mode": "Online / CSC Centers",
        "official_url": "https://pmsvanidhi.mohua.gov.in/"
    },
    {
        "id": "nrlm_aajeevika",
        "name": "Deendayal Antyodaya Yojana - NRLM (Aajeevika)",
        "ministry": "Ministry of Rural Development",
        "min_age": 18,
        "max_age": 60,
        "gender": ["Female"],
        "categories": ["General", "OBC", "SC", "ST"],
        "max_income": 250000,
        "states": ["All"],
        "area": ["Rural"],
        "business_status": ["New", "Existing"],
        "sectors": ["Handicraft", "Agro-processing", "Small Retail", "Services", "Livestock"],
        "subsidy_rate": "Interest subvention reducing net interest to 7% (or 4% on prompt repayment)",
        "benefits": "Revolving fund and Community Investment Support Fund (CIF) for Women Self-Help Groups (SHGs).",
        "documents": ["SHG Membership Record", "Aadhaar Card", "Bank Passbook", "Gram Panchayat Resident Certificate"],
        "application_mode": "Gram Panchayat / Block Mission Management Unit (BMMU)",
        "official_url": "https://aajeevika.gov.in/"
    },
    {
        "id": "nsfdc_micro",
        "name": "NSFDC Micro-Credit Finance Scheme",
        "ministry": "Ministry of Social Justice and Empowerment",
        "min_age": 18,
        "max_age": 60,
        "gender": ["Male", "Female", "Other"],
        "categories": ["SC"],
        "max_income": 300000,
        "states": ["All"],
        "area": ["Rural", "Urban"],
        "business_status": ["New", "Existing"],
        "sectors": ["Handicraft", "Services", "Manufacturing", "Small Retail", "Trading"],
        "subsidy_rate": "Concessional interest rate at 5% per annum",
        "benefits": "Targeted financial loan support up to ₹1.4 Lakh per beneficiary through State Channelizing Agencies.",
        "documents": ["Caste Certificate (SC)", "Income Certificate (Below Double Poverty Line)", "Aadhaar Card"],
        "application_mode": "State Channelizing Agency (SCA) / District Social Welfare Office",
        "official_url": "https://nsfdc.nic.in/"
    },
    {
        "id": "aspire_scheme",
        "name": "ASPIRE (Scheme for Promotion of Innovation & Rural Industry)",
        "ministry": "Ministry of Micro, Small and Medium Enterprises",
        "min_age": 18,
        "max_age": 60,
        "gender": ["Male", "Female", "Other"],
        "categories": ["General", "OBC", "SC", "ST"],
        "max_income": 1500000,
        "states": ["All"],
        "area": ["Rural"],
        "business_status": ["New"],
        "sectors": ["Agro-processing", "Manufacturing", "Services"],
        "subsidy_rate": "One-time financial grant up to ₹1 Crore for Livelihood Business Incubators (LBI)",
        "benefits": "Technical incubation support, prototyping, and handholding for rural agro-tech startups.",
        "documents": ["Business Incorporation Details", "Detailed Project Plan", "PAN/Aadhaar of Founders"],
        "application_mode": "Online",
        "official_url": "https://aspire.msme.gov.in/"
    },
    {
        "id": "pmfme",
        "name": "PM Formalisation of Micro Food Processing Enterprises (PMFME)",
        "ministry": "Ministry of Food Processing Industries (MoFPI)",
        "min_age": 18,
        "max_age": 65,
        "gender": ["Female", "Male", "Other"],
        "categories": ["SC", "ST", "OBC", "General"],
        "max_income": 1000000,
        "states": ["All"],
        "business_status": ["New", "Existing"],
        "sectors": ["Agro-processing", "Manufacturing"],
        "area": ["Rural", "Urban"],
        "subsidy_rate": "Credit-linked capital subsidy @ 35% (Max ₹10 Lakh)",
        "benefits": "Financial, technical, and business support for micro food processing units, self-help groups (SHGs), and farmer cooperatives.",
        "documents": ["Aadhaar Card", "Bank Account Statement", "Detailed Project Report (DPR)", "Food Safety (FSSAI) License"],
        "application_mode": "Online Portal",
        "official_url": "https://pmfme.mofpi.gov.in/"
    },
    {
        "id": "mudra_tarun",
        "name": "Pradhan Mantri Mudra Yojana (PMMY) - Tarun Category",
        "ministry": "Ministry of Finance",
        "min_age": 18,
        "max_age": 65,
        "gender": ["Female", "Male", "Other"],
        "categories": ["SC", "ST", "OBC", "General"],
        "max_income": 2000000,
        "states": ["All"],
        "business_status": ["Existing"],
        "sectors": ["Manufacturing", "Services", "Trading"],
        "area": ["Rural", "Urban"],
        "subsidy_rate": "Collateral-free loan from ₹5 Lakh up to ₹10 Lakh",
        "benefits": "Low interest institutional credit without collateral for established micro-enterprises looking to expand operations.",
        "documents": ["Aadhaar Card", "PAN Card", "Business Address Proof", "Last 12 Months Bank Statement", "Quotation of Machinery"],
        "application_mode": "Bank Branch / Udyamimitra Portal",
        "official_url": "https://www.mudra.org.in/"
    },
    {
        "id": "nayi_roshni",
        "name": "Nayi Roshni - Leadership Development for Minority Women",
        "ministry": "Ministry of Minority Affairs",
        "min_age": 18,
        "max_age": 65,
        "gender": ["Female"],
        "categories": ["OBC", "General", "SC", "ST"],
        "max_income": 250000,
        "states": ["All"],
        "business_status": ["New", "Existing"],
        "sectors": ["Services", "Handicraft", "Trading"],
        "area": ["Rural", "Urban"],
        "subsidy_rate": "100% Government funded training stipend & operational grants",
        "benefits": "Empowers and instills confidence in women, providing knowledge and skills for micro-enterprises and community leadership.",
        "documents": ["Aadhaar Card", "Income Certificate", "Community / Minority Declaration", "Bank Passbook"],
        "application_mode": "Online via Registered PIAs",
        "official_url": "https://nayiroshni-moma.gov.in/"
    },
    {
        "id": "samarth",
        "name": "SAMARTH Scheme for Capacity Building in Textile Sector",
        "ministry": "Ministry of Textiles",
        "min_age": 18,
        "max_age": 55,
        "gender": ["Female", "Male", "Other"],
        "categories": ["SC", "ST", "OBC", "General"],
        "max_income": 800000,
        "states": ["All"],
        "business_status": ["New"],
        "sectors": ["Handicraft", "Manufacturing"],
        "area": ["Rural", "Urban"],
        "subsidy_rate": "Free NSQF-aligned skill training & wage compensation",
        "benefits": "Skill development, modern loom training, and guaranteed wage employment or credit linkage for traditional textile workers.",
        "documents": ["Aadhaar Card", "Education / Skill Certificate", "Bank Details"],
        "application_mode": "Online (Samarth MIS Portal)",
        "official_url": "https://samarth-textiles.gov.in/"
    },
    {
        "id": "tread",
        "name": "Trade Related Entrepreneurship Assistance & Development (TREAD)",
        "ministry": "Ministry of Micro, Small and Medium Enterprises (MSME)",
        "min_age": 18,
        "max_age": 60,
        "gender": ["Female"],
        "categories": ["SC", "ST", "OBC", "General"],
        "max_income": 500000,
        "states": ["All"],
        "business_status": ["New", "Existing"],
        "sectors": ["Handicraft", "Agro-processing", "Services", "Trading"],
        "area": ["Rural", "Urban"],
        "subsidy_rate": "Government grant up to 30% of total project cost",
        "benefits": "Promotes self-employment among women through bank credit linkages and direct technical capacity-building grants.",
        "documents": ["Aadhaar Card", "NGO/SHG Endorsement", "Project Proposal", "Caste Certificate (if applicable)"],
        "application_mode": "Through Recognized Non-Governmental Organizations (NGOs)",
        "official_url": "https://msme.gov.in/"
    },
    {
        "id": "dairy_didf",
        "name": "Dairy Processing and Infrastructure Development Fund (DIDF)",
        "ministry": "Ministry of Fisheries, Animal Husbandry and Dairying",
        "min_age": 21,
        "max_age": 65,
        "gender": ["Female", "Male", "Other"],
        "categories": ["SC", "ST", "OBC", "General"],
        "max_income": 1500000,
        "states": ["All"],
        "business_status": ["New", "Existing"],
        "sectors": ["Agro-processing", "Manufacturing"],
        "area": ["Rural"],
        "subsidy_rate": "Subsidized loan interest rate (2.5% interest subvention)",
        "benefits": "Infrastructure support to set up chilling units, milk processing plants, and livestock value chains in rural areas.",
        "documents": ["Land Records", "FPO / Society Registration", "Bank Project Report", "Aadhaar Card"],
        "application_mode": "Via NABARD / NDDB / Scheduled Banks",
        "official_url": "https://dahd.nic.in/"
    },
    {
        "id": "van_dhan",
        "name": "Pradhan Mantri Van Dhan Yojana (PMVDY)",
        "ministry": "Ministry of Tribal Affairs / TRIFED",
        "min_age": 18,
        "max_age": 65,
        "gender": ["Female", "Male", "Other"],
        "categories": ["ST"],
        "max_income": 400000,
        "states": ["All"],
        "business_status": ["New", "Existing"],
        "sectors": ["Agro-processing", "Handicraft"],
        "area": ["Rural"],
        "subsidy_rate": "100% Grant up to ₹15 Lakh per Van Dhan Vikas Kendra (VDVK)",
        "benefits": "Value addition, branding, and packaging infrastructure for Non-Timber Forest Produce (herbs, honey, lac, wild fruits) for tribal gatherers.",
        "documents": ["Aadhaar Card", "ST Community Certificate", "SHG / Forest Committee Membership Proof", "Bank Passbook"],
        "application_mode": "Via State Nodal Agency / TRIFED Portal",
        "official_url": "https://trifed.tribal.gov.in/"
    },
    {
        "id": "pm_kusum_c",
        "name": "PM-KUSUM (Component C) - Solar Pump Feeder Solarization",
        "ministry": "Ministry of New and Renewable Energy (MNRE)",
        "min_age": 18,
        "max_age": 70,
        "gender": ["Female", "Male", "Other"],
        "categories": ["SC", "ST", "OBC", "General"],
        "max_income": 1200000,
        "states": ["All"],
        "business_status": ["New", "Existing"],
        "sectors": ["Agro-processing", "Services"],
        "area": ["Rural"],
        "subsidy_rate": "Direct central capital subsidy up to 30% to 50%",
        "benefits": "Enables individual farmers, cooperatives, and rural agri-enterprises to set up solar-powered grid-connected irrigation and agro-units.",
        "documents": ["Aadhaar Card", "Land Possession Certificate / Khasra Khatauni", "Electricity Connection Bill", "Bank Statement"],
        "application_mode": "State Renewable Energy Agency Portal",
        "official_url": "https://pmkusum.mnre.gov.in/"
    },
    {
        "id": "pm_egp_service",
        "name": "Mahila Coir Yojana (MCY)",
        "ministry": "Ministry of Micro, Small and Medium Enterprises (MSME)",
        "min_age": 18,
        "max_age": 60,
        "gender": ["Female"],
        "categories": ["SC", "ST", "OBC", "General"],
        "max_income": 300000,
        "states": ["All"],
        "business_status": ["New"],
        "sectors": ["Handicraft", "Manufacturing"],
        "area": ["Rural", "Urban"],
        "subsidy_rate": "75% Subsidy on the cost of motorized coir spinning equipment",
        "benefits": "Dedicated self-employment scheme for rural female artisans providing modern spinning equipment and two months stipendiary training.",
        "documents": ["Aadhaar Card", "Training Completion Certificate", "Bank Account Details", "Domicile Certificate"],
        "application_mode": "Coir Board Field Offices / MSME Udyam",
        "official_url": "https://coirboard.gov.in/"
    },
    {
        "id": "pm_vishwakarma_toolkit",
        "name": "Scheme for Promotion of Innovation, Rural Industry & Entrepreneurship (SFURTI)",
        "ministry": "Ministry of Micro, Small and Medium Enterprises (MSME)",
        "min_age": 21,
        "max_age": 65,
        "gender": ["Female", "Male", "Other"],
        "categories": ["SC", "ST", "OBC", "General"],
        "max_income": 2000000,
        "states": ["All"],
        "business_status": ["Existing"],
        "sectors": ["Handicraft", "Agro-processing", "Manufacturing"],
        "area": ["Rural"],
        "subsidy_rate": "Financial assistance up to ₹2.5 Crore (Regular Clusters) / ₹5 Crore (Major Clusters)",
        "benefits": "Sets up Common Facility Centers (CFCs), modern machinery plants, and market linkages for artisan collectives and rural producer companies.",
        "documents": ["Cluster DPR (Detailed Project Report)", "Registered Producer Company / Trust Deed", "Audited Financials", "Land Lease Deed"],
        "application_mode": "Online SFURTI Portal (Through Nodal Agencies like KVIC / Coir Board)",
        "official_url": "https://sfurti.msme.gov.in/"
    },
    {
        "id": "pm_matsya_sampada",
        "name": "Pradhan Mantri Matsya Sampada Yojana (PMMSY)",
        "ministry": "Ministry of Fisheries, Animal Husbandry and Dairying",
        "min_age": 18,
        "max_age": 65,
        "gender": ["Female", "Male", "Other"],
        "categories": ["SC", "ST", "OBC", "General"],
        "max_income": 1000000,
        "states": ["All"],
        "business_status": ["New", "Existing"],
        "sectors": ["Agro-processing", "Services"],
        "area": ["Rural"],
        "subsidy_rate": "60% Subsidy for SC/ST/Women entrepreneurs; 40% for General Category",
        "benefits": "Capital grants for setting up biofloc fish farming units, ornamental aquaculture, refrigerated transport, and cold chain fish retail kiosks.",
        "documents": ["Aadhaar Card", "Land / Water Body Lease or Ownership Proof", "Training Proof / DPR", "Caste Certificate (for 60% tier)"],
        "application_mode": "District Fisheries Office / PMMSY MIS Portal",
        "official_url": "https://pmmsy.dof.gov.in/"
    },
    {
        "id": "startup_seed_fund",
        "name": "Startup India Seed Fund Scheme (SISFS)",
        "ministry": "Ministry of Commerce and Industry (DPIIT)",
        "min_age": 18,
        "max_age": 65,
        "gender": ["Female", "Male", "Other"],
        "categories": ["SC", "ST", "OBC", "General"],
        "max_income": 5000000,
        "states": ["All"],
        "business_status": ["New"],
        "sectors": ["Services", "Manufacturing"],
        "area": ["Rural", "Urban"],
        "subsidy_rate": "Up to ₹20 Lakh grant for proof of concept; Up to ₹50 Lakh via convertible debentures",
        "benefits": "Financial assistance to early-stage tech and service startups for proof of concept, prototype development, product trials, and market entry.",
        "documents": ["DPIIT Recognition Certificate", "Incorporation Certificate", "Pitch Deck / Business Plan", "Founder PAN & Aadhaar"],
        "application_mode": "Startup India Portal Online",
        "official_url": "https://seedfund.startupindia.gov.in/"
    }
]